{
  "openapi": "3.0.0",
  "info": {
    "title": "API library manager",
    "description": "Essa API é um CRUD de livros",
    "contact": {
      "email": "gustavocabral97@hotmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://library-manager-production.up.railway.app",
      "description": "API de produção"
    },
    {
      "url": "http://localhost:3001",
      "description": "API de test"
    }
  ],
  "paths": {
    "/books": {
      "post": {
        "summary": "Cadastro de livros",
        "description": "Rota responsável por cadastrar um novo livro",
        "tags": ["Books"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Book"
              },
              "examples": {
                "book": {
                  "value": {
                    "name": "Dom Casmurro",
                    "author": "Machado de Assis",
                    "publishing": "Carambaia",
                    "releaseYear": 1899,
                    "numberOfPages": 210
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Property is required"
          },
          "409": {
            "description": "Book already exists"
          },
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/BookDB"
                },
                "examples": {
                  "bookDB": {
                    "value": {
                      "id": 1,
                      "name": "Dom Casmurro",
                      "author": "Machado de Assis",
                      "publishing": "Carambaia",
                      "releaseYear": 1899,
                      "numberOfPages": 210
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Busca todos os livros",
        "description": "Rota responsável por buscar todos os livros",
        "tags": ["Books"],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/BookDB"
                },
                "examples": {
                  "booksDB": {
                    "type": "array",
                    "value": [
                      {
                        "id": 1,
                        "name": "Dom Casmurro",
                        "author": "Machado de Assis",
                        "publishing": "Carambaia",
                        "releaseYear": 1899,
                        "numberOfPages": 210
                      },
                      {
                        "id": 2,
                        "name": "Dom Quixote de la Mancha",
                        "author": "Miguel de Cervantes",
                        "publishing": "Francisco de Robles",
                        "releaseYear": 1605,
                        "numberOfPages": 1033
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/books/{id}": {
      "get": {
        "summary": "Busca um livro pelo ID",
        "description": "Rota responsável por buscar um livro pelo ID",
        "tags": ["Books"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do produto",
            "required": true
          }
        ],
        "responses": {
          "404": {
            "description": "Book not found."
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/BookDB"
                },
                "examples": {
                  "bookDB": {
                    "value": {
                      "id": 1,
                      "name": "Dom Casmurro",
                      "author": "Machado de Assis",
                      "publishing": "Carambaia",
                      "releaseYear": 1899,
                      "numberOfPages": 210
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Altera um livro pelo ID",
        "description": "Rota responsável por alterar um livro pelo ID",
        "tags": ["Books"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do produto",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Book"
              },
              "examples": {
                "book": {
                  "value": {
                    "name": "Dom Quixote de la Mancha",
                    "author": "Miguel de Cervantes",
                    "publishing": "Francisco de Robles",
                    "releaseYear": 1605,
                    "numberOfPages": 1033
                  }
                }
              }
            }
          }
        },
        "responses": {
          "404": {
            "description": "Book not found."
          },
          "400": {
            "description": "Invalid property"
          },
          "204": {
            "description": "Successfully updated"
          }
        }
      },
      "delete": {
        "summary": "Deleta um livro pelo ID",
        "description": "Rota responsável por deletar um livro pelo ID",
        "tags": ["Books"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do produto",
            "required": true
          }
        ],
        "responses": {
          "404": {
            "description": "Book not found."
          },
          "204": {
            "description": "Successfully deleted"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Book": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "publishing": {
            "type": "string"
          },
          "releaseYear": {
            "type": "number"
          },
          "numberOfPages": {
            "type": "number"
          }
        }
      },
      "BookDB": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "publishing": {
            "type": "string"
          },
          "releaseYear": {
            "type": "number"
          },
          "numberOfPages": {
            "type": "number"
          }
        }
      }
    }
  }
}
